# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('embriologia', '0004_auto_20170515_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='feto',
            name='contenido',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
