# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embriologia', '0005_feto_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feto',
            name='contenido',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feto',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
