# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-18 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embriologia', '0014_feto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='feto',
            name='semestres',
            field=models.ManyToManyField(to='embriologia.Semestre'),
        ),
    ]
